### PR TITLE
feat: improve setup script

### PR DESCRIPTION
**Pull request by asbiin**
This makes the `monica:setup` script more reliable and install more things.
It also adds another devcontainer profile, so we can test code with dummy account immediately
image

### CODE REVIEW

**Review by djaiss — APPROVED** [review]
This is way better.
I love the fact that we have a ready to test setup, with the dummy data provisioned already.
This is fabulous.

**Comment by asbiin** [comment]
> This is way better. I love the fact that we have a ready to test setup, with the dummy data provisioned already. This is fabulous.

That's exactly why I did it ;)

**Comment by njelich** [comment]
Does this still work fine?

**Comment by njelich** [comment]
Does this still work fine?

**Comment by djaiss** [comment]
@njelich yes it does. What's going on?

**Pull request merged**
