### PR TITLE
refactor: remove 1 ignore from PHPStan config

### PR DESCRIPTION
**Pull request by szepeviktor**
Latest Larastan supports that.

### CODE REVIEW

**Comment by szepeviktor** [comment]
I think I should update Composer's lock file for that.

**Comment by djaiss** [comment]
You are the first external contributor on this new project :-)

Thanks for that and your interest.

Let's see why this PR doesn't pass the tests.

**Comment by szepeviktor** [comment]
> Let's see why this PR doesn't pass the tests.

It seems CI is made for local branches.
This PR comes from my fork.

**Comment by djaiss** [comment]
This shouldn't be a problem. We have kind of the same setup on the main Monica repo and we've had thousands of contributions. @asbiin can you help?

**Comment by asbiin** [comment]
@szepeviktor there might be an issue with the CI indeed, although your change is failing phpstan.

**Comment by szepeviktor** [comment]
> your change is failing phpstan.

I know: https://github.com/monicahq/chandler/pull/255#issuecomment-1283018185 That is why I've opened this PR.

Updating lock file ... 🏃🏻

**Comment by szepeviktor** [comment]
Done 🟢

**Comment by asbiin** [comment]
Everything looks fine now, thank you for this change!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
